### ISSUE TITLE
LIST VIEW NOT WORKING [BUG]

### ISSUE THREAD

**Issue by desimomo** [kid1194/frappe-better-list-view#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 18, in get_response
    response = renderer_instance.render()
      path = '/list'
      http_status_code = 200
      response = None
      endpoint = 'list'
      path_resolver = <frappe.website.path_resolver.PathResolver object at 0x7fb22d03b760>
      renderer_instance = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>
      e = DoesNotExistError('DocType None not found')
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 78, in render
    html = self.get_html()
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>
  File "apps/frappe/frappe/website/utils.py", line 510, in cache_html_decorator
    html = func(*args, **kwargs)
      args = (<frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>,)
      kwargs = {}
      html = None
      page_cache = None
      func = <function TemplatePage.get_html at 0x7fb23171f880>
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 89, in get_html
    self.update_context()
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 157, in update_context
    data = self.run_pymodule_method("get_context")
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>
  File "apps/frappe/frappe/website/page_renderers/template_page.py", line 219, in run_pymodule_method
    return method(self.context)
      self = <frappe.website.page_renderers.template_page.TemplatePage object at 0x7fb22d063820>
      method_name = 'get_context'
      inspect = <module 'inspect' from '/usr/lib/python3.10/inspect.py'>
      method = <function get_context at 0x7fb22d179120>
  File "apps/frappe/frappe/www/list.py", line 21, in get_context
    context.meta = frappe.get_meta(doctype)
      context = {'top_bar_items': [<TopBarItem: 7640ad8412 parent=Website Settings>, <TopBarItem: 5d35593e2f parent=Website Settings>, <TopBarItem: 23e2f47521 parent=Website Settings>, <TopBarItem: 32af5b00d3 parent=Website Settings>, <TopBarItem: 201660d38f parent=Website Settings>, <TopBarItem: 33e817700b parent=Website Settings>], 'footer_items': [<TopBarItem: c2cef792f0 parent=Website Settings>, <TopBarItem: 046fb0ef7b parent=Website Settings>, <TopBarItem: 2e0aed9725 parent=Website Settings>, <TopBarItem: d713ae5fad parent=Website Settings>, <TopBarItem: 399981147a parent=Website Settings>, <TopBarItem: 8e3b89a8ee parent=Website Settings>, <TopBarItem: 8fe12c75b3 parent=Website Settings>, <TopBarItem: 950daae9eb parent=Website Settings>], 'post_login': [{'label': 'My Account', 'url': '/me'}, {'label': 'Log out', 'url': '/?cmd=web_logout'}], 'banner_image': '/files/CK COLOR CRP.png', 'brand_html': "<img src='/files/CK COLOR CRP.png' style='max-height: 150px;'>", 'copyright': 'Desifoods Processing ...
      dict_params = {}
      doctype = None
  File "apps/frappe/frappe/__init__.py", line 1203, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
      doctype = None
      cached = True
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
  File "apps/frappe/frappe/model/meta.py", line 65, in get_meta
    meta = Meta(doctype)
      doctype = None
      cached = True
      meta = None
  File "apps/frappe/frappe/model/meta.py", line 123, in __init__
    super().__init__("DocType", doctype)
      self = <Meta: unsaved>
      doctype = None
      __class__ = <class 'frappe.model.meta.Meta'>
  File "apps/frappe/frappe/model/document.py", line 106, in __init__
    self.load_from_db()
      self = <Meta: unsaved>
      args = ('DocType', None)
      kwargs = {}
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/model/meta.py", line 129, in load_from_db
    super().load_from_db()
      self = <Meta: unsaved>
      __class__ = <class 'frappe.model.meta.Meta'>
  File "apps/frappe/frappe/model/document.py", line 149, in load_from_db
    frappe.throw(
      self = <Meta: unsaved>
      d = None
      __class__ = <class 'frappe.model.document.Document'>
  File "apps/frappe/frappe/__init__.py", line 522, in throw
    msgprint(
      msg = 'DocType None not found'
      exc = <class 'frappe.exceptions.DoesNotExistError'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
  File "apps/frappe/frappe/__init__.py", line 490, in msgprint
    _raise_exception()
      title = None
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      sys = <module 'sys' (built-in)>
      out = {'message': 'DocType None not found', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1}
      _strip_html_tags = <functools._lru_cache_wrapper object at 0x7fb22d0ba140>
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x7fb22d09a050>
      inspect = <module 'inspect' from '/usr/lib/python3.10/inspect.py'>
      msg = 'DocType None not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
      strip_html_tags = <function strip_html_tags at 0x7fb234883f40>
  File "apps/frappe/frappe/__init__.py", line 442, in _raise_exception
    raise raise_exception(msg)
      inspect = <module 'inspect' from '/usr/lib/python3.10/inspect.py'>
      msg = 'DocType None not found'
      raise_exception = <class 'frappe.exceptions.DoesNotExistError'>
frappe.exceptions.DoesNotExistError: DocType None not found
**Additional context**

**Comment by kid1194** [comment]
@desimomo Thank you for reporting this bug..

The error states that the doctype is None and I think that this error happens before loading the list view. 

The plugin doesn't modify the doctype value in JavaScript at all..

- Did this error appear after installing the plugin?
- Does this error appear evey time you open a doctype list?

**Comment by desimomo** [comment]
errorr appear after saving doc type before submitting , after 2  to 4
attempt it get submitted , this is happening after uninstall the list view
app,
we uninstall because after install list view, it  continue in refreshing
mode and list was not loading.

**Comment by kid1194** [comment]
@desimomo That is weird..

The plugin doesn't have any python methods that might cause any problem, it's just JavaScript files that extends the ListView JavaScript library..

- What is the version of frappe you are using? 
- Can you please supply the list settings you were using?

**Comment by desimomo** [comment]
V14

**Comment by desimomo** [comment]
V14

Please look into database
 https://www.centralkitchen.in/
user - ***@***.***
password - dpecon12

**Comment by kid1194** [comment]
@desimomo The user value is not visible..

Anyway, I have updated the plugin and if the problem of None doctype is from the plugin, an error message will appear stating that the doctype value is invalid..

**Comment by kid1194** [comment]
@desimomo Since you haven't responded for a long time, I will consider this issue solved an close this report..
