### ISSUE TITLE
[REQ] Detailed Docs

### ISSUE THREAD

**Issue by chechani** [kid1194/frappe-better-list-view#2]
We want to use Status based coluroing based on select field, can we achive different rows colur functiolity. What portion of exmpale code should be used in such a scanario

**Comment by kid1194** [comment]
@chechani Hello buddy..

Using this plugin, in the list view settings add `set_row_background` attribute with a function as its value..

```
function(row) {
    if (row.status === 'Cancelled') return 'danger';
}
```

[Set row background](https://github.com/kid1194/frappe-better-list-view#5-set_row_background)

**Comment by chechani** [comment]
Thanks, its working perfectly , how we can change color scheme of background row of our choice

**Comment by chechani** [comment]
its working
