### ISSUE TITLE
[Change Colors of Rows] how we can change color scheme of background row of our choice

### ISSUE THREAD

**Issue by chechani** [kid1194/frappe-better-list-view#3]
how we can change color scheme of background row of our choice

**Comment by kid1194** [comment]
@chechani This is currently not possible but I will make it possible in the coming update..

Just for you bro..
I will inform you when it's ready so you update the plugin..

**Comment by kid1194** [comment]
@chechani I have updated the plugin, now you can use css class, rgb, rgba or hsla..

**Comment by chechani** [comment]
It's not working now, as per your suggestion now anything like the following should work.

When we choose the selected status, its goes in the loop for fetching

frappe.listview_settings['Knee Lead'] = {
set_row_background: function(row) { 
  if (row.knee_lead_status === 'Open') return '#ffeeba' ; 
  if (row.knee_lead_status === 'Xray Requested') return 'warning'; 
  if (row.knee_lead_status === 'Xray Received (Opportunity)') return 'rgba(255,0,0,0.3)'; 
 // if (row.knee_lead_status === 'Black Listed') return 'danger'; 
}, 
};

**Comment by kid1194** [comment]
@chechani There was nothing that might cause a loop.. 

But I have updated the plugin, reverting back to the old way for setting the row background..

Please confirm if the loop problem exists after updating the plugin..

**Comment by chechani** [comment]
It's working now, thanks!
