### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FAYEZALADEEM** [kid1194/frappe-better-list-view#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kid1194** [comment]
@topfayez Thank you for reporting a bug..

But can you at least describe what it is and what version of frappe/erpnext you are using, so I can find the bug and fix it..

Best regards..

**Comment by kid1194** [comment]
@topfayez Since you haven't responded, I will consider this bug report a mistake..😁

Best regards..
