### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by parthvash1** [kid1194/frappe-better-list-view#5]
**Describe the bug**

**Comment by kid1194** [comment]
@parthvash1 Hello buddy..

Thanks for reporting a bug, but can you please tell me what and where is the bug exactly so I can fix it..

Best regards..

**Comment by kid1194** [comment]
@parthvash1 Hey buddy. I'm still waiting for your reply.. 

I don't want you to be disappointed with this plugin 😁

Best regards..

**Comment by kid1194** [comment]
@parthvash1 Hey buddy..

Since this issue has been open for a long time and you haven't clarified the bug you reported, the issue will be closed..

Best regards..
